import {
  workersTypeQuery,
  userAuthenticationType,
  workerContactType,
  workerDegreesType,
  workerGeneralType,
  userGeneralType,
  workerLocationType,
  workerResumeType,
  workerHighSchoolType,
  workerCertificationsType,
  workerCoursesType,
  workerAchievementsType,
  workerWorksExamplesType,
  workerJobType,
  workerLearningInterestType,
  workerExperienceType,
  workerSkillType,
  workerFollowType,
  userFollowType,
  jobsTypeQuery,
  jobCreateType,
  jobUpdateType,
  jobDeleteType,
} from './index';

const typeDefs: any = [
  // Worker Type Definitions
  workersTypeQuery,
  userAuthenticationType,
  workerContactType,
  workerDegreesType,
  workerGeneralType,
  userGeneralType,
  workerLocationType,
  workerResumeType,
  workerHighSchoolType,
  workerCertificationsType,
  workerCoursesType,
  workerAchievementsType,
  workerWorksExamplesType,
  workerJobType,
  workerLearningInterestType,
  workerExperienceType,
  workerSkillType,
  workerFollowType,
  userFollowType,
  jobsTypeQuery,
  jobCreateType,
  jobUpdateType,
  jobDeleteType,
];

export default typeDefs;
