import {
  // Worker Resolvers
  userAuthenticationResolver,
  workerGeneralResolver,
  userGeneralResolver,
  workerLocationResolver,
  workerContactResolver,
  workerDegreesResolver,
  workerResumeResolver,
  workerHighSchoolResolver,
  workerCertificationsResolver,
  workerCoursesResolver,
  workerAchievementsResolver,
  workerWorksExamplesResolver,
  workerJobResolver,
  workerLearningInterestResolver,
  workerExperienceResolver,
  workerSkillResolver,
  workerFollowResolver,
  // Worker Queries
  userFollowResolver,
  jobResolver,
  // Worker Queries
  getWorkerByIdResolverQuery,
  getJobsResolverQuery,
  workersResolverQuery,
  userAuthenticationUnion,
  // Worker Unions
  workerUnion,
  workersUnion,
  workerDegreesUnion,
  workerResumeUnion,
  workerHighSchoolUnion,
  workerCertificationsUnion,
  workerCoursesUnion,
  workerAchievementsUnion,
  workerWorksExamplesUnion,
  workerJobUnion,
  workerLearningInterestUnion,
  workerExperienceUnion,
  workerSkillUnion,
  workerFollowUnion,
  userFollowUnion,
  jobUnions,
} from './index';

const resolvers = [
  // Worker Resolvers
  userAuthenticationResolver,
  workerGeneralResolver,
  userGeneralResolver,
  workerLocationResolver,
  workerContactResolver,
  workerDegreesResolver,
  workerResumeResolver,
  workerHighSchoolResolver,
  workerCertificationsResolver,
  workerCoursesResolver,
  workerAchievementsResolver,
  workerWorksExamplesResolver,
  workerJobResolver,
  workerLearningInterestResolver,
  workerExperienceResolver,
  workerSkillResolver,
  workerFollowResolver,
  // Worker Queries
  getWorkerByIdResolverQuery,
  userFollowResolver,
  jobResolver,
  // Worker Queries
  getWorkerByIdResolverQuery,
  getJobsResolverQuery,
  workersResolverQuery,
  userAuthenticationUnion,
  // Worker Unions
  workerUnion,
  workersUnion,
  workerDegreesUnion,
  workerResumeUnion,
  workerHighSchoolUnion,
  workerCertificationsUnion,
  workerCoursesUnion,
  workerAchievementsUnion,
  workerWorksExamplesUnion,
  workerJobUnion,
  workerLearningInterestUnion,
  workerExperienceUnion,
  workerSkillUnion,
  workerFollowUnion,
  userFollowUnion,
  jobUnions,
];

export default resolvers;
